services:
  - type: web
    name: humanchain
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars: []
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
